import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "@/providers/redux";
import { SessionProvider } from "@/providers/session";
import { getServerSession } from "next-auth";
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "@/providers/theme";
import Navigation from "@/components/navigation";
import { AuthConfig } from "./api/auth/[...nextauth]/route";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout(props: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  const session = await getServerSession(AuthConfig);

  return (
    <html lang="en">
      <body className={inter.className + " pb-5"}>
        <ThemeProvider>
          <Toaster />
          <SessionProvider session={session}>
            <ReduxProvider>
              <Navigation session={session} />
              <div className="sm:px-10 px-4">{props.children}</div>
              {props.modal}
            </ReduxProvider>
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
